import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'

const roboto = Roboto({ weight: ['300'], subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='light'>
      <body className={`${roboto.className} w-full h-screen text-[--blue] bg-[--light-blue] scroll-smooth`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
